default_agent: aws
agents:
  aws:
    name: aws
    entrypoint: E:/agent-core-aws/faq_agentcore_app_with_logging.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: E:\agent-core-aws
    aws:
      execution_role: arn:aws:iam::107456217679:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-7d1507284a
      execution_role_auto_create: false
      account: '107456217679'
      region: us-east-1
      ecr_repository: 107456217679.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-aws
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: aws-HaR0vD29L0
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:107456217679:runtime/aws-HaR0vD29L0
      agent_session_id: b06c0371-36e6-4eae-8af3-da327bab040c
    codebuild:
      project_name: bedrock-agentcore-aws-builder
      execution_role: arn:aws:iam::107456217679:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-7d1507284a
      source_bucket: bedrock-agentcore-codebuild-sources-107456217679-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
